### ISSUE TITLE
sscan record support should use "t" with trigger channels, not "d"

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/APS_BlueSky_tools#53]
note that the support uses "d" which is prob a copy/paste typo

**Comment by klauer** [comment]
It isn't nearly as nice as what you have in place, but you might find it interesting.
I auto-generated (and hand-tweaked a bit) all records I had access to at some point. Here's sscan:

https://github.com/klauer/recordwhat/blob/master/recordwhat/records/sscan.py
