### ISSUE TITLE
Devices documentation will not build

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/APS_BlueSky_tools#67]
RTD fails to build documentation for [Devices](https://aps-bluesky-tools.readthedocs.io/en/latest/source_code/devices.html).  It's hung on this error:

```
WARNING: autodoc: failed to import module 'devices' from module 'APS_BlueSky_tools'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/aps-bluesky-tools/conda/latest/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aps-bluesky-tools/checkouts/latest/APS_BlueSky_tools/devices.py", line 666, in <module>
    class TunableEpicsMotor(AxisTunerMixin, EpicsMotor):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

Work this out in a branch.

**Comment by prjemian** [comment]
@tacaswell @danielballan  @klauer  Can y'all advise me how to properly construct a mixin class?  [This code](https://github.com/BCDA-APS/APS_BlueSky_tools/blob/master/APS_BlueSky_tools/devices.py#L572-L661) functions the way I expect it to yet RTD [warns on this line](https://github.com/BCDA-APS/APS_BlueSky_tools/blob/master/APS_BlueSky_tools/devices.py#L664) as shown above and won't build the docs for [Devices](https://aps-bluesky-tools.readthedocs.io/en/latest/source_code/devices.html).

**Comment by prjemian** [comment]
see: http://www.phyast.pitt.edu/~micheles/python/metatype.html

**Comment by prjemian** [comment]
Also see this book: [*Putting metaclasses to work*](https://duckduckgo.com/?q=Putting+metaclasses+to+work&t=ffsb&ia=products) ,  By Ira R. Forman, Scott H. Danforth,    Published Oct 13, 1998 by Addison-Wesley Professional.  

probably out of print

**Comment by tacaswell** [comment]
That is very odd that you can import it locally, but it fails on RTD.  

What version of python is RTD running?  Can you build the docs locally?

**Comment by prjemian** [comment]
(base) mintadmin@mint-vm ~/.../APS_BlueSky_tools/docs $ ipython
Python 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 17:14:51) 
Running Sphinx v1.7.5

Building the docs locally is the way to resolve the issue.  Central to the problem is that all mixin classes here will need refactoring, thus the beam line instances as well.  

RTD is failing on code that is provided for legacy support.  That legacy ends now for this pre-release package.  Instead, the legacy support will be expressed in the documentation (which is better in the long run anyway).

**Comment by prjemian** [comment]
@tacaswell - This failed because various packages are [mocked out](http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports) for building docs on RTD.  

```
autodoc_mock_imports = "h5py numpy matplotlib pandas bluesky ophyd databroker pyRestTable".split()
```

When EpicsMotor is mocked, for example, then a demo mixin based on that will fail as shown above.

```
class myEpicsMotor(EpicsDescriptionMixin, EpicsMotor): pass
```

A custom conda environment where ophyd is installed will fix this.  Proven using a local build.
